import type { FormPageOption } from "../types/advertisement";

export const DEFAULT_FORM_PAGES: FormPageOption[] = [
  {
    value: "home",
    label: "Home page",
    sections: [
      {
        value: "article_list",
        label: "Main article list / headlines",
        where: [
          { value: "after_article", label: "After article #", needs: "article_number" },
          { value: "before_article", label: "Before article #", needs: "article_number" },
        ],
        sizes: ["728x90", "970x250", "468x60", "320x100", "custom"],
        default_size: "728x90",
        suggested_mobile_size: "320x100",
      },
      {
        value: "category",
        label: "Home category block (e.g. Sports, Politics)",
        needs_category: true,
        where: [
          { value: "after_article", label: "After article #", needs: "article_number" },
          { value: "before_article", label: "Before article #", needs: "article_number" },
          { value: "after_section", label: "After section (full width banner)" },
          { value: "before_section", label: "Before section (full width banner)" },
          { value: "sidebar_top", label: "Category sidebar top" },
          { value: "sidebar_middle", label: "Category sidebar middle" },
          { value: "sidebar_bottom", label: "Category sidebar bottom" },
        ],
        sizes: ["728x90", "970x250", "300x250", "300x600", "468x60", "320x100", "custom"],
        default_size: "728x90",
        suggested_mobile_size: "320x100",
      },
      {
        value: "latest",
        label: "Home latest articles strip",
        where: [
          { value: "after_article", label: "After article #", needs: "article_number" },
          { value: "before_article", label: "Before article #", needs: "article_number" },
          { value: "sidebar_top", label: "Latest sidebar top" },
          { value: "sidebar_middle", label: "Latest sidebar middle" },
          { value: "sidebar_bottom", label: "Latest sidebar bottom" },
        ],
        sizes: ["728x90", "970x250", "300x250", "300x600", "468x60", "320x100", "custom"],
        default_size: "728x90",
        suggested_mobile_size: "320x100",
      },
      {
        value: "sidebar",
        label: "Sidebar",
        where: [
          { value: "sidebar_top", label: "Sidebar Top" },
          { value: "sidebar_middle", label: "Sidebar Middle" },
          { value: "sidebar_bottom", label: "Sidebar Bottom" },
        ],
        sizes: ["300x250", "300x600", "custom"],
        default_size: "300x250",
        suggested_mobile_size: "300x250",
      },
      {
        value: "header",
        label: "Header",
        hide_where: true,
        where: [{ value: "header", label: "Header" }],
        sizes: ["970x250", "728x90", "custom"],
        default_size: "970x250",
        suggested_mobile_size: "320x100",
      },
      {
        value: "footer",
        label: "Footer",
        hide_where: true,
        where: [{ value: "footer", label: "Footer" }],
        sizes: ["728x90", "970x250", "custom"],
        default_size: "728x90",
        suggested_mobile_size: "320x100",
      },
    ],
  },
  {
    value: "category",
    label: "Category page",
    needs_entity: "category",
    sections: [
      {
        value: "article_list",
        label: "Category article list",
        needs_category: true,
        where: [
          { value: "after_article", label: "After article #", needs: "article_number" },
          { value: "before_article", label: "Before article #", needs: "article_number" },
          { value: "after_section", label: "After section (full width banner)" },
          { value: "before_section", label: "Before section (full width banner)" },
        ],
        sizes: ["728x90", "970x250", "468x60", "320x100", "custom"],
        default_size: "728x90",
        suggested_mobile_size: "320x100",
      },
      {
        value: "sidebar",
        label: "Sidebar",
        needs_category: true,
        where: [
          { value: "sidebar_top", label: "Sidebar Top" },
          { value: "sidebar_middle", label: "Sidebar Middle" },
          { value: "sidebar_bottom", label: "Sidebar Bottom" },
        ],
        sizes: ["300x250", "300x600", "custom"],
        default_size: "300x250",
        suggested_mobile_size: "300x250",
      },
      {
        value: "header",
        label: "Header",
        hide_where: true,
        needs_category: true,
        where: [{ value: "header", label: "Header" }],
        sizes: ["970x250", "728x90", "custom"],
        default_size: "970x250",
        suggested_mobile_size: "320x100",
      },
      {
        value: "footer",
        label: "Footer",
        hide_where: true,
        needs_category: true,
        where: [{ value: "footer", label: "Footer" }],
        sizes: ["728x90", "970x250", "custom"],
        default_size: "728x90",
        suggested_mobile_size: "320x100",
      },
    ],
  },
  {
    value: "single",
    label: "Article detail page",
    needs_entity: "article",
    entity_searchable: true,
    sections: [
      {
        value: "article_content",
        label: "Inside article content",
        where: [
          { value: "after_paragraph", label: "After paragraph #", needs: "paragraph_number" },
          { value: "before_paragraph", label: "Before paragraph #", needs: "paragraph_number" },
          { value: "article_top", label: "Top of article" },
          { value: "article_middle", label: "Middle of article" },
          { value: "article_bottom", label: "Bottom of article" },
        ],
        sizes: ["728x90", "970x250", "468x60", "320x100", "custom"],
        default_size: "728x90",
        suggested_mobile_size: "320x100",
      },
      {
        value: "sidebar",
        label: "Sidebar",
        where: [
          { value: "sidebar_top", label: "Sidebar Top" },
          { value: "sidebar_middle", label: "Sidebar Middle" },
          { value: "sidebar_bottom", label: "Sidebar Bottom" },
        ],
        sizes: ["300x250", "300x600", "custom"],
        default_size: "300x250",
        suggested_mobile_size: "300x250",
      },
      {
        value: "header",
        label: "Header",
        hide_where: true,
        where: [{ value: "header", label: "Header" }],
        sizes: ["970x250", "728x90", "custom"],
        default_size: "970x250",
        suggested_mobile_size: "320x100",
      },
      {
        value: "footer",
        label: "Footer",
        hide_where: true,
        where: [{ value: "footer", label: "Footer" }],
        sizes: ["728x90", "970x250", "custom"],
        default_size: "728x90",
        suggested_mobile_size: "320x100",
      },
    ],
  },
  {
    value: "search",
    label: "Search results",
    sections: [
      {
        value: "article_list",
        label: "Search article list",
        where: [
          { value: "after_article", label: "After article #", needs: "article_number" },
          { value: "before_article", label: "Before article #", needs: "article_number" },
        ],
        sizes: ["728x90", "970x250", "468x60", "320x100", "custom"],
        default_size: "728x90",
        suggested_mobile_size: "320x100",
      },
      {
        value: "sidebar",
        label: "Sidebar",
        where: [
          { value: "sidebar_top", label: "Sidebar Top" },
          { value: "sidebar_middle", label: "Sidebar Middle" },
          { value: "sidebar_bottom", label: "Sidebar Bottom" },
        ],
        sizes: ["300x250", "300x600", "custom"],
        default_size: "300x250",
        suggested_mobile_size: "300x250",
      },
      {
        value: "header",
        label: "Header",
        hide_where: true,
        where: [{ value: "header", label: "Header" }],
        sizes: ["970x250", "728x90", "custom"],
        default_size: "970x250",
        suggested_mobile_size: "320x100",
      },
      {
        value: "footer",
        label: "Footer",
        hide_where: true,
        where: [{ value: "footer", label: "Footer" }],
        sizes: ["728x90", "970x250", "custom"],
        default_size: "728x90",
        suggested_mobile_size: "320x100",
      },
    ],
  },
  {
    value: "tag",
    label: "Tag page",
    needs_entity: "tag",
    sections: [
      {
        value: "article_list",
        label: "Tag article list",
        where: [
          { value: "after_article", label: "After article #", needs: "article_number" },
          { value: "before_article", label: "Before article #", needs: "article_number" },
        ],
        sizes: ["728x90", "970x250", "468x60", "320x100", "custom"],
        default_size: "728x90",
        suggested_mobile_size: "320x100",
      },
      {
        value: "sidebar",
        label: "Sidebar",
        where: [
          { value: "sidebar_top", label: "Sidebar Top" },
          { value: "sidebar_middle", label: "Sidebar Middle" },
          { value: "sidebar_bottom", label: "Sidebar Bottom" },
        ],
        sizes: ["300x250", "300x600", "custom"],
        default_size: "300x250",
        suggested_mobile_size: "300x250",
      },
      {
        value: "header",
        label: "Header",
        hide_where: true,
        where: [{ value: "header", label: "Header" }],
        sizes: ["970x250", "728x90", "custom"],
        default_size: "970x250",
        suggested_mobile_size: "320x100",
      },
      {
        value: "footer",
        label: "Footer",
        hide_where: true,
        where: [{ value: "footer", label: "Footer" }],
        sizes: ["728x90", "970x250", "custom"],
        default_size: "728x90",
        suggested_mobile_size: "320x100",
      },
    ],
  },
  {
    value: "author",
    label: "Author page",
    needs_entity: "author",
    sections: [
      {
        value: "article_list",
        label: "Author article list",
        where: [
          { value: "after_article", label: "After article #", needs: "article_number" },
          { value: "before_article", label: "Before article #", needs: "article_number" },
        ],
        sizes: ["728x90", "970x250", "468x60", "320x100", "custom"],
        default_size: "728x90",
        suggested_mobile_size: "320x100",
      },
      {
        value: "sidebar",
        label: "Sidebar",
        where: [
          { value: "sidebar_top", label: "Sidebar Top" },
          { value: "sidebar_middle", label: "Sidebar Middle" },
          { value: "sidebar_bottom", label: "Sidebar Bottom" },
        ],
        sizes: ["300x250", "300x600", "custom"],
        default_size: "300x250",
        suggested_mobile_size: "300x250",
      },
      {
        value: "header",
        label: "Header",
        hide_where: true,
        where: [{ value: "header", label: "Header" }],
        sizes: ["970x250", "728x90", "custom"],
        default_size: "970x250",
        suggested_mobile_size: "320x100",
      },
      {
        value: "footer",
        label: "Footer",
        hide_where: true,
        where: [{ value: "footer", label: "Footer" }],
        sizes: ["728x90", "970x250", "custom"],
        default_size: "728x90",
        suggested_mobile_size: "320x100",
      },
    ],
  },
  {
    value: "latest",
    label: "Latest articles",
    sections: [
      {
        value: "article_list",
        label: "Latest article list",
        where: [
          { value: "after_article", label: "After article #", needs: "article_number" },
          { value: "before_article", label: "Before article #", needs: "article_number" },
        ],
        sizes: ["728x90", "970x250", "468x60", "320x100", "custom"],
        default_size: "728x90",
        suggested_mobile_size: "320x100",
      },
      {
        value: "sidebar",
        label: "Sidebar",
        where: [
          { value: "sidebar_top", label: "Sidebar Top" },
          { value: "sidebar_middle", label: "Sidebar Middle" },
          { value: "sidebar_bottom", label: "Sidebar Bottom" },
        ],
        sizes: ["300x250", "300x600", "custom"],
        default_size: "300x250",
        suggested_mobile_size: "300x250",
      },
      {
        value: "header",
        label: "Header",
        hide_where: true,
        where: [{ value: "header", label: "Header" }],
        sizes: ["970x250", "728x90", "custom"],
        default_size: "970x250",
        suggested_mobile_size: "320x100",
      },
      {
        value: "footer",
        label: "Footer",
        hide_where: true,
        where: [{ value: "footer", label: "Footer" }],
        sizes: ["728x90", "970x250", "custom"],
        default_size: "728x90",
        suggested_mobile_size: "320x100",
      },
    ],
  },
];

export const MOBILE_SIZES = [
  { value: "", label: "None / Default" },
  { value: "320x100", label: "320×100 (Large Mobile Banner)" },
  { value: "300x250", label: "300×250 (Medium Rectangle)" },
  { value: "320x50", label: "320×50 (Standard Mobile Banner)" },
  { value: "custom", label: "Custom mobile size" },
];

export const STATUS_OPTIONS = [
  { value: "active", label: "Active" },
  { value: "draft", label: "Draft" },
  { value: "paused", label: "Paused" },
  { value: "ended", label: "Ended" },
  { value: "pending_approval", label: "Pending Approval" },
  { value: "rejected", label: "Rejected" },
  { value: "archived", label: "Archived" },
];
